version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm chromatic -a CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes
